language: go
sudo: required
services:
  - docker
go:
  - 1.6
before_install:
  - openssl aes-256-cbc -K $encrypted_790acdb9ad25_key -iv $encrypted_790acdb9ad25_iv
    -in catalogue_deploy_rsa.enc -out catalogue_deploy_rsa -d
  - go get -v github.com/Masterminds/glide
  - glide install
  - go get -u github.com/mattn/goveralls

install: true

env:
  - GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=catalogue;

script:
  - set -e
  - ./scripts/build.sh;
  - ./test/test.sh unit.py
 # - ./test/test.sh component.py
  - ./test/test.sh container.py --tag $TAG

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
  - ./scripts/push.sh
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
addons:
  ssh_known_hosts: $BASTION
deploy:
  provider: script
  skip_cleanup: true
  # The deploy.sh file actually points to the deploy file on the bastion. Not one in the repo.
  script: ssh -o StrictHostKeyChecking=no $BASTION_USER@$BASTION ./deploy.sh ${REPO} $COMMIT
  on:
    branch: master
notifications:
  slack:
    secure: uwlcWCyyEW0xssAi6pNIzMtw5r5Zak07+b34sR8uiyCnxrFHPypa7/spV0dn7KHDjcDM+A5J+fCQQ2nvQ0EoDOoGndaDmtOYpgDSG17DdXB1uk3P3dADyuhLMFl9U7TYpxGVDvCoEPx9r2s/1ACEWq8QWpxt7oDVTWNCcMiO/XUoQgHoP7mu573xAOK2OE2cu62R412ycz0TNY295SOsTPoze+cfVCfg+RfQoo9l0UDZK2OClYS6DNFoyG2OGhh4mVB8tjzmzwRDbgrNXrBU5HuP2h9Nk04u8284wuBVg0C4oTiRIzpDTNmowdq0T24uE/RZMwNIgnYt1d+djzlGPB97lGTIFQvQKP9u/D7JtWnjpHvrKbn2TC/dJTF5nCiai4D8WKwDc4Kl/a0ALJiUM2NUd3vmK0O1sWwu4UqMEbMB3Vj9Gq2UylnS1k2TaNmkI4hfLCL3brqTMicULLubIfA5HZSEegvAwly/kPQpfi6AJ7/vedWLnCGr3VnuWwMAYntru/3fKbYBMUJMEkT9XqQiblqsArjUDz8l2CyhVT34q/ZIiYR83EAX6mDkk2mBgp7DiT3VKMQ1dyGtLa1AjtbUphWRNyOM/j2ZX9aTBozNV7iAvDDujMQurTmjZshO/WO5qSOs4F57lYSQpu26Wx5vyPa4oY2chsZLK+rVdDU=
