version: '2'

services:
    catalogue:
        build:
            context: .
            dockerfile: ./docker/catalogue/Dockerfile
        image: weaveworksdemos/catalogue
        hostname: catalogue
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - ZIPKIN=http://zipkin:9411/api/v1/spans
            - reschedule=on-node-failure
        ports:
            - "8080:80"
    catalogue-db:
        build:
            context: ./docker/catalogue-db/
        image: weaveworksdemos/catalogue-db
        hostname: catalogue-db
        restart: always
        environment:
            - reschedule=on-node-failure
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=socksdb
    zipkin:
        image: openzipkin/zipkin 
        hostname: zipkin
        restart: always
        cap_drop:
            - all
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
        read_only: true
        tmpfs:
            - /tmp:rw,noexec,nosuid
        environment:
            - reschedule=on-node-failure
        ports:
            - "9411:9411"
    zipkinseed:
        image: alpine
        command: /bin/sh -c 'sleep 10 ; wget http://catalogue/health ; wget http://catalogue/catalogue ; wget http://catalogue/catalogue/size ; wget http://catalogue/tags'

